### ISSUE TITLE
Addition of function to generate random string of specified length.

### ISSUE THREAD

**Issue by SharonIV0x86** [SharonIV0x86/StringWiz#9]
Add a string function to generate a string of specified length.

Something like this.
```c
char* str_random(int length)
```

**Comment by rahul-devrani** [comment]
hey, could you please assign to me?

**Comment by SharonIV0x86** [comment]
> hey, could you please assign to me?

Sure go ahead.

**Comment by SharonIV0x86** [comment]
@rahul-devrani How is the progress on this?

**Comment by rahul-devrani** [comment]
Added requested feature. you can review it.
